sonar.projectKey=my-agent-poc-rag-search
sonar.projectName=My Agent POC - RAG Search Service
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=.ci-reports/**,**/__pycache__/**,**/.pytest_cache/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=.ci-reports/coverage.xml
sonar.python.xunit.reportPath=.ci-reports/pytest.xml
sonar.scm.provider=git
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
