apiVersion: v1
kind: Service
metadata:
  name: online-library
  namespace: rag-poc
spec:
  selector:
    app: online-library
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  type: ClusterIP
