apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-ai-agent-config
  namespace: rag-poc
data:
  TZ: "America/New_York"
  LLM_PROVIDER: ollama
  OLLAMA_MODEL: gemma4:latest
  OLLAMA_BASE_URL: http://host.docker.internal:11434

